controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\Room;
use app\models\RoomBookingForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider();
        $dataProvider->query = Room::find()->orderBy(['name' => SORT_ASC]);
        $dataProvider->pagination->pageSize = 5;
        $dataProvider->pagination->pageSizeParam = false;

        return $this->render('index', compact('dataProvider'));
    }

    /**
     * @param $id
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionTryToBook($id)
    {
        $room = $this->findRoom($id);

        $success = false;
        $model = new RoomBookingForm($room);

        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $booking = $model->makeInstance();
                if ($booking->save()) {
                    $message = sprintf('Поздравляем! Номер зарегистрирован на имя %s, дата заселения - %s, дата выезда - %s', $booking->name,
                        $booking->start, $booking->end);
                    Yii::$app->session->addFlash('success', $message);
                    $model->reset();
                } else {
                    foreach ($booking->firstErrors as $firstError) {
                        Yii::$app->session->addFlash('error', $firstError);
                    }
                }
            } else {
                foreach ($model->firstErrors as $firstError) {
                    Yii::$app->session->addFlash('error', $firstError);
                }
            }
        }

        return $this->render('try-to-book', compact('room', 'model', 'success'));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            $rememberMeTime = $model->rememberMe ? Yii::$app->params['REMEMBER_ME_TIME'] : 0;
            Yii::$app->user->login($user, $rememberMeTime);

            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @param $id
     *
     * @return Room
     * @throws NotFoundHttpException
     */
    private function findRoom($id) : Room
    {
        $room = Room::findOne($id);
        if ($room === null) {
            throw new NotFoundHttpException('Номер не найден');
        }

        return $room;
    }
}

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

</div>

views/site/index.php
<?php

use app\models\Room;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ListView;

/* @var $this View */
/* @var $dataProvider ActiveDataProvider */

$this->title = 'Главная';
?>
<div class="site-index">

    <h1>Номера для заказа</h1>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => static function (Room $model, $key, $index, $widget) {
            return implode(PHP_EOL, [
                Html::beginTag('div', ['class' => 'panel panel-default']),
                Html::beginTag('div', ['class' => 'panel-heading']),
                Html::tag('h3', $model->name, ['class' => 'panel-title']),
                Html::endTag('div'),
                Html::beginTag('div', ['class' => 'panel-body']),
                Html::tag('p', $model->description),
                Html::endTag('div'),
                Html::beginTag('div', ['class' => 'panel-footer text-right']),
                Html::a('Заказать', ['site/try-to-book', 'id' => $model->id], ['class' => 'btn btn-info']),
                Html::endTag('div'),
                Html::endTag('div'),
            ]);
        },
    ]) ?>

</div>

views/site/login.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-info">Для входа введите <strong>admin/admin</strong></div>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
    ]); ?>

    <?= $form->field($model, 'username')
        ->textInput()
        ->label('Имя пользователя')
    ?>

    <?= $form->field($model, 'password')
        ->passwordInput(['autofocus' => true])
        ->label('Пароль')
    ?>

    <?= $form->field($model, 'rememberMe')
        ->checkbox()
        ->label('Запомнить меня')
    ?>

    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-9">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/try-to-book.php
<?php

use app\models\Room;
use app\models\RoomBookingForm;
use kartik\date\DatePicker;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\MaskedInput;

/* @var $this View */
/* @var $room Room */
/* @var $model RoomBookingForm */
/* @var $success bool */

$this->title = "Заказ комнаты «‎{$room->name}»‎";

?>
<div class="site-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'room-booking-form',
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tel')->widget(MaskedInput::class, [
        'mask' => '+7(999)999-99-99',
    ]) ?>

    <?= $form->field($model, 'start')->widget(DatePicker::class, [
        'options' => ['data-datepicker' => '', 'placeholder' => 'Выберите дату заселения'],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true,
            'startDate' => date('Y-m-d'),
        ],
    ]) ?>

    <?= $form->field($model, 'for_one_day')->checkbox(['data-for-one-day' => '']) ?>

    <div data-for-one-day-target="">
        <?= $form->field($model, 'end')->widget(DatePicker::class, [
            'options' => ['data-datepicker' => '', 'placeholder' => 'Выберите дату выезда'],
            'pluginOptions' => [
                'format' => 'yyyy-mm-dd',
                'todayHighlight' => true,
                'startDate' => date('Y-m-d'),
            ],
        ]) ?>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Заказать</button>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    window.onload = function () {
        $('[data-for-one-day]').on('input', function () {
            const isChecked = $(this).is(':checked');
            if (isChecked) {
                $('[data-for-one-day-target]').hide();
            } else {
                $('[data-for-one-day-target]').show();
            }
        }).trigger('input');
    }
</script>